### PR TITLE
Fix genre identification where genre returned array

### LINKED ISSUE #59: Song with multiple genres causes runtime error
Some of my songs come back from the server with multiple genres applied:

```
$ telnet 0 6600
Trying 0.0.0.0...
Connected to 0.
Escape character is '^]'.
OK MPD 0.19.0
search file "pull me under"
file: doza/Dream Theater/Images and Words/01 Pull Me Under.mp3
Last-Modified: 2012-11-11T16:44:44Z
Time: 493
Artist: Dream Theater
AlbumArtist: Dream Theater
Title: Pull Me Under
Album: Images and Words
Track: 1
Date: 1992
Genre: Rock
Genre: Rock
Composer: Dream Theater; Kevin Moore
```

This results in an array in the `genre` metadata:

```ruby
song = @mpd.where(file:'pull me under').first
p song.instance_variable_get(:@data)[:genre]
#=> ["Rock", "Rock"]
```

This causes some code in the new genre resolver to fail when asking for `song.genre`.

/var/lib/gems/2.1.0/gems/ruby-mpd-0.3.3/lib/ruby-mpd/song.rb:264:in `[]': no implicit conversion of Regexp into Integer (TypeError)

### PR DESCRIPTION
**Pull request by Phrogz**
Fixes #59 by always using the first genre from an array.

### CODE REVIEW

**Comment by Phrogz** [comment]
In my library of 17k songs (from multiple sources) about 1% had multiple genres. In all cases there were exactly two genres. In only two cases were the two genres not identical:

```
["Pop", "Funk"]
["AlternRock", "Alt. Rock"]
```

Given this, it seems to me that throwing away the second genre seems a reasonable choice.

**Comment by archSeer** [comment]
I'd think having multiple genre values would be less common, but still something to be expected. What do you think about having `#genres` always return an array, and have a `#genre` method that returns `genres.first`?

Nice work on the PRs by the way, I'll take some time this evening to go through it all :)

**Comment by Phrogz** [comment]
I like the idea of adding `genres`. I'll add that and re-submit.

**Comment by archSeer** [comment]
Looks good, but would you mind fixing the test suite as well?

**Comment by archSeer** [comment]
Nevermind, restarted the test and it's passing now :beers:

**Pull request merged**
